### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by kolod** [Serkov/Dao#1]
стр. 73
Согласно байкам, оло-
вянная чума — одна из причин поражения Наполеоновской ар-
мии в условиях суровых российских **_городов_** (представьте, как на
морозе ваши пуговицы, ложки, вилки, кружки превращаются в
серый порошок).

Наверно **_холодов_**.

**Comment by deoevgen** [comment]
Вы ошиблись почтой.

сб, 5 мая 2018 г., 23:40 Alexandr Kolodkin <notifications@github.com>:

**Comment by Scordavis** [comment]
@Dresvyannikov не умеете гитом пользоваться, да? )))

**Comment by deoevgen** [comment]
Сообразил)))

вс, 6 мая 2018 г., 0:03 Scordavis <notifications@github.com>:

**Comment by ShNURoK42** [comment]
Так себе опечатка :)
