### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by EnochTheWise** [Serkov/Dao#6]
На странице 47, в комментарии к рисунку 2.20:
"... Справа - содержимое корпуса..."
Собственно картинка "содержимого", не справа а ниже.

**Comment by EnochTheWise** [comment]
Стр. 50
"Мельчайшие шарики ртути из щелей можно вытянуть при помощи сп**и**ринцовки..."
наверное "спринцовки", спИринцовки я не нагуглил 8)

**Comment by EnochTheWise** [comment]
Стр. 52
"... когда ртуть так или иначе попадает в организм человека, животных или **в растений**"
мб "организм человека, животного или в растения(е)", а лучше по другому написать... кажись

**Comment by EnochTheWise** [comment]
Стр. 62
"... скорости химических реакций растут, и **кислород воздуха**"
мб "кислород **из** воздуха"

**Comment by EnochTheWise** [comment]
Стр. 86
"... Органические полусинтетические (**тоесть** основанные..."
должно быть: "то есть"

**Comment by EnochTheWise** [comment]
Стр. 93
"воздействие **температуры, давления, горючего** внутри камеры сгорания"
выглядит как излишнее перечисление, может убрать слово "горючего"?

**Comment by EnochTheWise** [comment]
Стр. 110
"...но в силу дороговизны и токсичности пыли из нее применяется редко."
наверное лучше так:
"...но в силу дороговизны и токсичности пыли, применяется редко."

**Comment by EnochTheWise** [comment]
Стр. 111
В контексте "Асбест":
"Использовал**ось** во множестве применений,..."
мб "Использовал**ся**" лучше

**Comment by EnochTheWise** [comment]
Стр. 117
"... условно **назовем** полусинтетическими **назовем** такие материалы..."
одно "назовем" лишнее ;o)

**Comment by EnochTheWise** [comment]
Стр. 121
"... наружную оплетку из искусственной нити - **из** нейлона, капрона"
второе "из" кажется лишнее

**Comment by EnochTheWise** [comment]
Стр. 160
"... к стиролу при полимеризации добавлен соп**р**олимер акрилонитрил..."
наверное: "сополимер"

**Comment by EnochTheWise** [comment]
Стр. 200
Сноска 104:
"... торговая марка, ставшая местами нарицательн**ым**"
скорее "нарицательн**ой**"

**Comment by EnochTheWise** [comment]
И немного в README.md
"если вы **з**отите получить pdf файл" - "хотите"
"BY-NC-SA, **тоесть** вы можете спокойно скачивать, распространять" - "то есть"

**Comment by Serkov** [comment]
Опечатки исправил, спасибо)
